name: 'Terraform'

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Apply
        run: |
          cd infrastructure/environments/prod
          terraform init
          terraform apply -auto-approve -var="region=eu-north-1" -var="cluster_name=innovatemart-eks-new" -var="vpc_cidr=10.0.0.0/16"