name: 'Terraform Plan and Apply'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init & Plan
        if: github.event_name == 'pull_request'
        run: |
          cd infrastructure/environments/prod
          terraform init
          terraform plan -no-color -input=false
      - name: Terraform Init & Apply
        if: github.event_name == 'push'
        run: |
          cd infrastructure/environments/prod
          terraform init
          terraform apply -auto-approve -input=false